#define BEGINING 1
#define BODY 2
#define END 3
#define MOVE 4
#define TO 5
#define ADD 6
#define INPUT 7
#define PRINT 8
#define IDENTIFIER 9
#define INTEGER_SIZE 10
#define INTEGER 11
#define SEMICOLON 12
#define STRING_LITERAL 13
#define TERMINATOR 14
